// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyErp.EF.DataAccess;

#nullable disable

namespace MyErp.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyErp.Core.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AreaId")
                        .HasColumnType("longtext");

                    b.Property<string>("AreaName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("MyErp.Core.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Floor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Governate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LandMark")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MainBranchId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mangername")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RegionCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TIN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("branchType")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phonenumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("MyErp.Core.Models.CashAndBanks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("AccountNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalInflow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalOutflow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("currencyname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("exchangeRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("madeen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("treasuryCode")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("CashAndBanks");
                });

            modelBuilder.Entity("MyErp.Core.Models.CashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CashAndBankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsInflow")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OrdermeId")
                        .HasColumnType("int");

                    b.Property<string>("ordertype")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CashAndBankId");

                    b.HasIndex("OrdermeId");

                    b.ToTable("CashFlows");
                });

            modelBuilder.Entity("MyErp.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Internal_Id")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MyErp.Core.Models.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ExchangeRate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("MyErp.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("BuildingNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<int>("CustomerType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int>("EntityType")
                        .HasColumnType("int");

                    b.Property<string>("Governate")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone2")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone3")
                        .HasColumnType("longtext");

                    b.Property<string>("RegionCity")
                        .HasColumnType("longtext");

                    b.Property<string>("SchemeID")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("companyAdress")
                        .HasColumnType("longtext");

                    b.Property<string>("companyCeoName")
                        .HasColumnType("longtext");

                    b.Property<string>("companyCeoNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("companyName")
                        .HasColumnType("longtext");

                    b.Property<string>("companyTaxNo")
                        .HasColumnType("longtext");

                    b.Property<string>("companyType")
                        .HasColumnType("longtext");

                    b.Property<string>("companyopenningbalance")
                        .HasColumnType("longtext");

                    b.Property<string>("opening_credit")
                        .HasColumnType("longtext");

                    b.Property<string>("opening_debit")
                        .HasColumnType("longtext");

                    b.Property<string>("parentAcc")
                        .HasColumnType("longtext");

                    b.Property<string>("treasurycode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("treeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MyErp.Core.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("InternalId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("MyErp.Core.Models.Orderme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountRec")
                        .HasColumnType("longtext");

                    b.Property<int>("CashAndBankId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerCountry")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes1")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes2")
                        .HasColumnType("longtext");

                    b.Property<int?>("POSId")
                        .HasColumnType("int");

                    b.Property<string>("SalesAcc")
                        .HasColumnType("longtext");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("barcode")
                        .HasColumnType("longtext");

                    b.Property<int?>("baseordertype")
                        .HasColumnType("int");

                    b.Property<int?>("currencyBalance")
                        .HasColumnType("int");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<string>("internalId")
                        .HasColumnType("longtext");

                    b.Property<string>("invoice")
                        .HasColumnType("longtext");

                    b.Property<int?>("offerprice")
                        .HasColumnType("int");

                    b.Property<int?>("orderType")
                        .HasColumnType("int");

                    b.Property<string>("receipt")
                        .HasColumnType("longtext");

                    b.Property<string>("taxcode")
                        .HasColumnType("longtext");

                    b.Property<decimal>("totDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("treasuryAcc")
                        .HasColumnType("longtext");

                    b.Property<int?>("wayofpayemnt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CashAndBankId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("Ordermes");
                });

            modelBuilder.Entity("MyErp.Core.Models.Ordermedetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OrdermeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Productname")
                        .HasColumnType("longtext");

                    b.Property<decimal>("afterTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("beforeTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdProddate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("expiredate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("internalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("serialnumber")
                        .HasColumnType("longtext");

                    b.Property<decimal>("tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("unitcode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrdermeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("categoryId");

                    b.ToTable("Ordermedetails");
                });

            modelBuilder.Entity("MyErp.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DescaraptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("HALFwholesaleprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Sectoral")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TableTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Tax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UnitCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("created")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("discount4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("expire")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("image")
                        .HasColumnType("longtext");

                    b.Property<int?>("limit")
                        .HasColumnType("int");

                    b.Property<int?>("profitpercatanage")
                        .HasColumnType("int");

                    b.Property<decimal?>("purchaseprice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice6")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice7")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("sellingprice9")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("serialnumber")
                        .HasColumnType("longtext");

                    b.Property<string>("statment")
                        .HasColumnType("longtext");

                    b.Property<string>("statment2")
                        .HasColumnType("longtext");

                    b.Property<bool?>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("wholesaleprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MyErp.Core.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("internalId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("MyErp.Core.Models.SalesMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<int>("phone_num")
                        .HasColumnType("int");

                    b.Property<string>("salesmanId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SalesMen");
                });

            modelBuilder.Entity("MyErp.Core.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("FinalValue")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrdermeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("StockActionsId")
                        .HasColumnType("int");

                    b.Property<int?>("StockActiontransferId")
                        .HasColumnType("int");

                    b.Property<int?>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitTypes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdProddate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("expiredate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("internalId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("productName")
                        .HasColumnType("longtext");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("serialnumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrdermeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockActionsId");

                    b.HasIndex("StockActiontransferId");

                    b.ToTable("StockActionDetails");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .HasColumnType("longtext");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("StoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockActiontype")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("physicalinvNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("StockActions");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActiontransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("StoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoName2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("ToStockId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("physicalinvNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StockId");

                    b.HasIndex("ToStockId");

                    b.HasIndex("UserId");

                    b.ToTable("StockActiontransfers");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockReq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockReqs");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockReqDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StockReqDetails");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockTaking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Curenncy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("currencyId")
                        .HasColumnType("int");

                    b.Property<int>("exchangeRate")
                        .HasColumnType("int");

                    b.Property<int>("internalId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("stockId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("currencyId");

                    b.HasIndex("productId");

                    b.HasIndex("stockId");

                    b.ToTable("StockTakings");
                });

            modelBuilder.Entity("MyErp.Core.Models.Treasury", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Treasuries");
                });

            modelBuilder.Entity("MyErp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GroupRolId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rights")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MyErp.Core.Models.CashAndBanks", b =>
                {
                    b.HasOne("MyErp.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("MyErp.Core.Models.CashFlow", b =>
                {
                    b.HasOne("MyErp.Core.Models.CashAndBanks", "CashAndBank")
                        .WithMany()
                        .HasForeignKey("CashAndBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Orderme", "Orderme")
                        .WithMany()
                        .HasForeignKey("OrdermeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashAndBank");

                    b.Navigation("Orderme");
                });

            modelBuilder.Entity("MyErp.Core.Models.Orderme", b =>
                {
                    b.HasOne("MyErp.Core.Models.CashAndBanks", "CashAndBank")
                        .WithMany()
                        .HasForeignKey("CashAndBankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashAndBank");

                    b.Navigation("Currency");

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyErp.Core.Models.Ordermedetail", b =>
                {
                    b.HasOne("MyErp.Core.Models.Orderme", "Orderme")
                        .WithMany("Ordermedetails")
                        .HasForeignKey("OrdermeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orderme");

                    b.Navigation("Product");

                    b.Navigation("category");
                });

            modelBuilder.Entity("MyErp.Core.Models.Product", b =>
                {
                    b.HasOne("MyErp.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MyErp.Core.Models.ProductType", b =>
                {
                    b.HasOne("MyErp.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActionDetails", b =>
                {
                    b.HasOne("MyErp.Core.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Orderme", "Orderme")
                        .WithMany()
                        .HasForeignKey("OrdermeId");

                    b.HasOne("MyErp.Core.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.StockActions", "StockActions")
                        .WithMany("StockActionDetails")
                        .HasForeignKey("StockActionsId");

                    b.HasOne("MyErp.Core.Models.StockActiontransfer", "StockActiontransfer")
                        .WithMany("StockActionDetails")
                        .HasForeignKey("StockActiontransferId");

                    b.Navigation("Category");

                    b.Navigation("Orderme");

                    b.Navigation("Product");

                    b.Navigation("StockActions");

                    b.Navigation("StockActiontransfer");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActions", b =>
                {
                    b.HasOne("MyErp.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("MyErp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Employee");

                    b.Navigation("Stock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActiontransfer", b =>
                {
                    b.HasOne("MyErp.Core.Models.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Stock", "ToStock")
                        .WithMany()
                        .HasForeignKey("ToStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Employee");

                    b.Navigation("Stock");

                    b.Navigation("ToStock");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockTaking", b =>
                {
                    b.HasOne("MyErp.Core.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Currency", "currency")
                        .WithMany()
                        .HasForeignKey("currencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyErp.Core.Models.Stock", "stock")
                        .WithMany()
                        .HasForeignKey("stockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("category");

                    b.Navigation("currency");

                    b.Navigation("product");

                    b.Navigation("stock");
                });

            modelBuilder.Entity("MyErp.Core.Models.Treasury", b =>
                {
                    b.HasOne("MyErp.Core.Models.Treasury", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MyErp.Core.Models.Orderme", b =>
                {
                    b.Navigation("Ordermedetails");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActions", b =>
                {
                    b.Navigation("StockActionDetails");
                });

            modelBuilder.Entity("MyErp.Core.Models.StockActiontransfer", b =>
                {
                    b.Navigation("StockActionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
